spring:
  profiles:
    active: linux

---
#linux \u73AF\u5883
server:
  port: 80
spring:
  profiles: linux
  mvc:
    favicon:
      enabled: false
  #\u8FC7\u6EE4\u6389\u8FD4\u56DE\u7ED3\u679C null \u503C
  jackson:
    default-property-inclusion: non_null
  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/views/
    suffix: .html
    cache: false
logging:
  file: /var/log/xu7x.log
  #path: /var/log

---
# \u5F00\u53D1\u73AF\u5883
server:
  port: 7777
spring:
  profiles: dev
  mvc:
    favicon:
      enabled: false
  #\u8FC7\u6EE4\u6389\u8FD4\u56DE\u7ED3\u679C null \u503C
  jackson:
    default-property-inclusion: non_null
  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/views/
    suffix: .html
    cache: false
logging:
  file: c:\log\xu7x.log
  #path: D:\code\git\xu7x\
  level:
    org.springboot.web: info
